### ISSUE TITLE
WPA-PWD and RSA KEY does not work with -w flag on Linux.

### ISSUE THREAD

**Issue by jochman** [pocc/tshark.dev#53]
I tried to run `tshark -r $INFILE -w $OUTFILE -o uat:rsa_keys:"/path/to/key/key/key",""' -o wlan.enable_decryption:TRUE -o uat:80211_keys:"wpa-pwd","PASSWORD"`
Then I used `tshark -r $OUTFILE --export-objects http,./folder/`
I could not extract the objects.

I tried it on Linux (latest Ubuntu 20.04 and alpine 3.11, 3.12, edge).

On my Mac, it worked. I even copied the OUTFILE to my mac and I could export the objects after the decryption. When I copied a decrypted file from my mac to Linux I still did not manage to export the objects inside.

The command did work if I added the `--export-objects` option to the command above.
Tried to run on files with wpa-pwd and rsa key separately, so it's not a problem with the combination of those two.

Does anyone know why there's a difference between mac and Linux?

**Comment by pocc** [comment]
It looks like you're using the wrong flag. You're using -t in the 2nd line
instead of -r to read the file.

**Comment by jochman** [comment]
I miss typed it in the thread, but I used -r in the command.

**Comment by pocc** [comment]
Can you provide an online storage link to the decrypted pcap?

**Comment by jochman** [comment]
of course, it's this file from wireshark wiki:
https://wiki.wireshark.org/HowToDecrypt802.11
The file [SampleCaptures/wpa-Induction.pcap](https://wiki.wireshark.org/SampleCaptures?action=AttachFile&do=get&target=wpa-Induction.pcap) has WPA traffic encrypted using the password "Induction" and SSID "Coherer".

**Comment by pocc** [comment]
Looking at this again, there's two problems. 

1. You're using both `-o uat:80211_keys` and `-o uat:rsa_keys` when only the former is necessary for this sample capture.
2. The `-w` flag for WPA2 decryption will not write the decrypted file, but will decrypt when the output is text (if `-w` is not used or if you specify output with `-T text`, which is the default output type).

To demonstrate, diff finds no differences on pcap write (tested on mac and linux):

```bash
$ tshark -r wpa-Induction.pcap -w exported.pcap -o wlan.enable_decryption:TRUE \
    -o "uat:80211_keys:\"wpa-pwd\",\"Induction:Coherer\"" -F pcap
$ diff wpa-Induction.pcap exported.pcap 
$
```

But does find differences on the text output of each (one decrypted DHCP packet is shown decrypted in the diff for brevity):

```bash
$ tshark -r wpa-Induction.pcap -T text > original.txt
$ tshark -r wpa-Induction.pcap -w exported.pcap -o wlan.enable_decryption:TRUE \
    -o "uat:80211_keys:\"wpa-pwd\",\"Induction:Coherer\"" -F pcap -T text > decrypted.txt
$ diff original.txt decrypted.txt
<    99   5.844024 Apple_82:36:3a → Broadcast    802.11  404 Data, SN=27, FN=0, Flags=.p.....TC ff:ff:ff:ff:ff:ff ← 00:0d:93:82:36:3a
---
>    99   5.844024      0.0.0.0 → 255.255.255.255 DHCP  404 DHCP Request  - Transaction ID 0x3b0f7566 ff:ff:ff:ff:ff:ff ← 00:0d:93:82:36:3a
102c102
...
<output suppressed>
```

This is not regarding a specific article in this repo so I'm going to close this issue. 

If you have other questions about how to use tshark, you should use https://ask.wireshark.org. If you have a feature request, you can make an enchancement-type bug report at https://bugs.wireshark.org/bugzilla.
