### ISSUE TITLE
Rotating tshark temp file with display filter

### ISSUE THREAD

**Issue by huaraz** [pocc/tshark.dev#54]
Hi Team,
 
    tshark is a great tool and I use it with display filters to monitor traffic.  As far as I can see it creates a temp file for this which permanently grows.  I wonder if this file can be rotated like with the -w option ?  Or is this temp file containing only required information for the 2nd pass i.e. growth is limited ? 

Thank you
Markus

**Comment by pocc** [comment]
You should run `tshark --help` to see all of the options. You may also want to look at [limiting the size](https://tshark.dev/capture/limit_size/).

As this does not have to do with a specific article, I will be closing this issue.

**Comment by huaraz** [comment]
It is a non existing feature.  So can such a feature be added ? 

Thank you
Markus

**Comment by pocc** [comment]
The appropriate place for this question is the wireshark forums: https://ask.wireshark.org. You probably want to use a capture filter instead.
